// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace Goldfinch.Models
{
    public partial class Home
    {
        public const string Codename = "home";
        public const string BaseTeaserImageCodename = "base__teaser_image";
        public const string BaseTitleCodename = "base__title";
        public const string BodyCopyCodename = "body_copy";
        public const string SeoCanonicalUrlCodename = "seo__canonical_url";
        public const string SeoMetaDescriptionCodename = "seo__meta_description";
        public const string SeoMetaTitleCodename = "seo__meta_title";

        public IEnumerable<IAsset> BaseTeaserImage { get; set; }
        public string BaseTitle { get; set; }
        public IRichTextContent BodyCopy { get; set; }
        public string SeoCanonicalUrl { get; set; }
        public string SeoMetaDescription { get; set; }
        public string SeoMetaTitle { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}